### ISSUE TITLE
Packet error

### ISSUE THREAD

**Issue by sikang99** [Sandertv/go-raknet#19]
When i use conn.Write(), it causes the following errors
2022/08/25 19:50:01 error handling packet: error handling packet in datagram: error handling packet: error measuring rtt: ping timestamp is in the future
....

Just byte send testing is ok.

**Comment by Sandertv** [comment]
Could you give more information on what data you're writing? It sounds like you're (unintentionally) writing a raknet ping packet with an invalid timestamp, which the other end then responds to with that same invalid timestamp.

**Comment by sikang99** [comment]
Currently i use raknet in media streaming application. when the media data is jpeg, it is ok. very good. But when the media data is h.264 codec data, it causes the above error. I don't use ping, just conn.Write() to send data.

**Comment by sikang99** [comment]
Regardless of data types, sending code part is same as follows.

	for d.ok {
		sample, err := d.mothsink.PullSample()
		if err != nil {
			log.Println(err)
			break
		}

		// fmt.Println("sample:", sample.Duration, len(sample.Data))
		n, err := conn.Write(sample.Data) <---- this causes packet errors
		if err != nil {
			log.Println(n, err)
			break
		}
	}

**Comment by Sandertv** [comment]
RakNet has several built-in packets which are essentially reserved, so generally the data you write to it should be prefixed with a byte that is not used as a RakNet packet ID as described in the original C++ library here: https://github.com/facebookarchive/RakNet/blob/master/Source/MessageIdentifiers.h#L39-L48. Minecraft, for example, prefixes all its packets with a `0xfe` byte.

What's happening here is that your h.264 codec data coincidentally starts with the same ID as a RakNet ping (but isn't a valid ping packet). The other end of the connection will then respond with a RakNet pong which is also invalid.

**Comment by sikang99** [comment]
@Sandertv according to your comment, I solved the problem by padding 4 character code as the prefix. 
I think need to study raknet protocol itself.
Thank you.
