### ISSUE TITLE
connectedPing is sent 100 times every 4 seconds

### ISSUE THREAD

**Issue by gioiann** [Sandertv/go-raknet#2]
I'm new to go and I've no experience with go tickers but I'm sure [this](https://github.com/Sandertv/go-raknet/blob/master/conn.go#L151) condition is true 100 times every 4 seconds by default and it's not supposed to be.
`t.Unix()` is the current time in seconds and will be the same 100 times every second

**Comment by Sandertv** [comment]
Hmmm, you're right. I never noticed that, well spotted. I'll fix it right away.
