### ISSUE TITLE
Packets are sometimes unnecessarily resent in a loop

### ISSUE THREAD

**Issue by gioiann** [Sandertv/go-raknet#4]
Currently a packet is resent if no ACK is received before `Round-Trip Time + 10ms` since it was sent.
This is "fine" for most of the servers sending ACKs every [10ms](https://github.com/pmmp/RakLib/blob/b4799d6ecc0914b6d47ead8c70b50e53b043d828/src/server/SessionManager.php#L53) (PocketMine)
But there are some servers, like SteadFast2 which instead will send ACKs every [25ms](https://github.com/Hydreon/Steadfast2/blob/756e5153d80e3fe0ba26002a22c301bb342ba205/src/raklib/server/SessionManager.php#L109)

The RTT is not perfect, changes continuously overtime and only indicates a rough estimate of the ping latency which is different than the ACK one

So, on some servers packets will be resent forever since it's impossible to receive an ACK in time.

The effect of this is not noticeable because the client and server will automatically discard duplicate packets.

**Comment by gioiann** [comment]
Also, on lbsg (Steadfast2 servers) the connected pong is wrongly encoded so this raknet is not able to measure the RTT at all resulting in a fixed delay of 30ms. So if an ACK isn't received in 30ms the packets will be resent.
So since Steadfast2 sends ACKs every 25ms , in this case an ACK needs to arrive at a fixed 5ms delay which will never happen.

**Comment by Sandertv** [comment]
Fixed by 6c06f8336a136b3235f95c929edf683489d797db, thanks for the additional information on Steadfast, that was helpful.
