### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by gioiann** [Sandertv/go-raknet#6]
I just updated go-raknet to the latest release available and this error occurs:
```
panic: error establishing a connection: connection timed out

goroutine 1 [running]:
main.main()
	/home/gio/Desktop/test/gophertunnel/main.go:39 +0x56b
```

You can reproduce by using the proxy from the gophertunnel repo and connecting to "hivebedrock.network:19132"

Before the update I was using the one from [this commit](https://github.com/Sandertv/go-raknet/commit/7a47adc79859bf29716c1ed9e822eb432af324e7) and it worked

This error is from [here](https://github.com/Sandertv/go-raknet/blob/78c6c1ab85f457122d211617fbddf7d40793f291/dial.go#L134)

I don't know why the raknet connection is timing out, the ConnectionRequestAccepted is received correctly.

**Comment by Sandertv** [comment]
It seems The Hive doesn't send a correct ConnectionRequestAccepted packet. I'll add a workaround for it.

**Comment by Sandertv** [comment]
I've pushed a new tag (v1.6.10) which includes the commit resolving this issue.
